### ISSUE TITLE
Known Issues: 5/10/16

### ISSUE THREAD

**Issue by dbouwman** [tomwayson/advanced-d-n-d#12]
List of issues to divide and conquer:
### Cards & Rows @ dbouwman

remaining issues w/ dragging/deleting cards
- [x] can't delete last card in row
- [x] can't drag/move last card in row to another row/section
- [x] drag to new section (sometimes) results in >12 cards wide #13
- [x] hide / remove `card-resizer` when a card is dragged away #14
- [x] rename `event-bus` `layout-coordinator`
### Sections @ tomwayson
- [x] only handle drag of cards/sections #11
- [x] if a section is empty, it shows a drop-target for cards that will create a new row for the card behind the scenes
- drag / drop section into layout
  - [x] copy crack highlight logic from bscard-editor, tho sections just need top/bottom
  - [x] copy insert before/after logic from bs-row-editor
  - [x] make sure drop listener needs to handle sections as well as cards, or more generally, ensure dropping of sections/cards doesn't conflict w/ each other
- Finalize how we send "card settings" along with the card-toolbox entry
  - [x] create a second debugger card (image), set it up as a new "card" type that can be dragged out, and dropped

remove section
- [x] add section controls w/ `X` to remove
- [x] add remove section from page when clicked

move section
- [x] add a handle and drag from handle only
- [x] drop listener needs to handle move section
### cross-browser (see #7 for details)
- [x] firefox
- [x] safari
- [ ] IE11 (VMs ftw)
### UI/UX Smoothness
- [ ] reduce jank
  - measure jank w/ chrome
  - leverage animation frames
  - reduce recompute of `componentPosition` by attaching to window events for re-size vs `.volatile()` css transitions on column widths
    - try to optimize order of `.width` change when adding / removing card from row
- [ ] When dragging and mouse is directly over the `drop-target` we see it flashing as the browser switches between 
  - seeing the mouse as "close to the card's edge", thus SHOWing the drop-target 
  - seeing the mouse as over the drop-target, and thus NOT close to the edge of the card, thus hiding it

Plus any [open bugs](https://github.com/tomwayson/advanced-d-n-d/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

**Comment by dbouwman** [comment]
- can't delete last card in row
- can't drag/move last card in row to another row/section

**Comment by dbouwman** [comment]
- drag / drop section into layout
- add drop-target for sections
- section settings ui?

**Comment by dbouwman** [comment]
- reduce jank
  - leverage animation frames
  - reduce recompute of `componentPosition` by attaching to window events for re-size vs `.volatile()`
- css transitions on column widths
     - try to optimize order of `.width` change when adding / removing card from row

**Comment by dbouwman** [comment]
- cross-browser
   - firefox
   - safari
   - IE11 (VMs ftw)

**Comment by tomwayson** [comment]
move section
- [ ] add a handle and drag from handle only
- [ ] drop listener needs to handle move section

**Comment by dbouwman** [comment]
- drag from one section to another sometimes results in a row < 12 cols wide

![image](https://cloud.githubusercontent.com/assets/119129/15149448/d1742588-1686-11e6-97f7-e4ffc8e269b6.png)

**Comment by tomwayson** [comment]
#11 still applies

**Comment by dbouwman** [comment]
- hide / remove `card-resizer` when a card is dragged away
In this image, the resizer remains, but now the card is full width because it's partner was dragged up
![image](https://cloud.githubusercontent.com/assets/119129/15149547/2695cb84-1687-11e6-8f4c-d3566dfe85d4.png)

**Comment by dbouwman** [comment]
When dragging and mouse is directly over the `drop-target` we see it flashing as the browser switches between 
- seeing the mouse as "close to the card's edge", thus SHOWing the drop-target 
- seeing the mouse as over the drop-target, and thus NOT close to the edge of the card, thus hiding it

**Comment by dbouwman** [comment]
Finalize how we send "card settings" along with the card-toolbox entry:

- create a second debugger card (image), set it up as a new "card" type that can be dragged out, and dropped

**Comment by tomwayson** [comment]
spacer card?
