### ISSUE TITLE
Layout TODO List

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/advanced-d-n-d#5]
Here's what's on my radar:
### Plan
- get features working in chrome
- get features working in supported browsers (C,FF,S,O)latest + IE11
- refactor into mixins/base classes
- finalize ui elements (DOM + CSS)
  - drag handle icons
  - dragimages
  - resize handles
- extract components + css into `ember-arcgis-page-layout` addon
- pull  `ember-arcgis-page-layout` addon into `opendata-ui`
- pull  `ember-arcgis-page-layout` addon into `opendata-admin`

drop-indicators
- [x] address scroll position offset

page setup
- [x] add colors to full-width sections so we can differentiate them

add card
- [x] split targetCard and add new card on left/right
- [x] row-above / row-below drop zone mouse-target should be "inset" from the edges
- ~~if too wide (i.e. cols > 12), do we create a new row?~~ Always split card unless it is @ Min-Width
- [x] automatically add containers if none (i.e. if blank page add section/row)

delete card
- [x] expand neighbor to fill void
  - [x] expand left neighbor, unless deleted card is left most
- [x] if last card in row, send `onRowDelete` action up stack

re-size card (width only)
- [x] show splitter / drag handle on mouseover
  - [x] only show splitter between cards
-  ~~on drag, move in 1/12th increments~~ Drag events--
-  ~~on dragend, set widths of the two cards involved~~ Drag events--
- [x] on click of re-sizer buttons, change widths of the two cards involved

move cards
- [x] drag from handle only
- [x] drag start should indicate this is a move, not an add
- [x] drop listener needs to handle move (i.e. remove then add, see rows controller for logic)
- [x] move from one section to another

general
- [x] drag handles should appear as if dragging whole item (section/card)

Please correct/add as needed @dbouwman

**Comment by tomwayson** [comment]
closing as remaining TODOs have been moved to #12
